# 7 Introduction to NumPy

## The NumPy Array

In [1]:
import numpy as np

a = np.array([1, 2, 3])
a + a

array([2, 4, 6])

In [7]:
def print_array_details(a):
    print(f'Dimentions: {a.ndim}, shape: {a.shape}, dtype: {a.dtype}')

In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
print_array_details(a)

Dimentions: 1, shape: (8,), dtype: int64


In [11]:
a = a.reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a = a.reshape([2, 2, 2])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x.shape

(2, 3)

In [14]:
x.shape = (6,)
x

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [15]:
x = x.astype('int64')
x.dtype

dtype('int64')

In [16]:
x

array([1, 2, 3, 4, 5, 6])

### Creating Arrays

In [17]:
a = np.zeros([2, 3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a.dtype

dtype('float64')

In [20]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
empty_array = np.empty((2,3))
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.random.random((2, 3))

array([[0.08341242, 0.25675392, 0.08500244],
       [0.31518343, 0.60675484, 0.82048928]])

In [24]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [25]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

### Array Indexing and Slicing

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a[2]

3

In [27]:
a[3:5]

array([4, 5])

In [29]:
a[:4:2] = 0
a

array([0, 2, 0, 4, 5, 6])

In [30]:
a[::-1]

array([6, 5, 4, 0, 2, 0])

In [36]:
a = np.arange(8)
a.shape = (2, 2, 2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a[1] == a[1,:]

array([[ True,  True],
       [ True,  True]])

In [38]:
a[1] == a[1, :, :]

array([[ True,  True],
       [ True,  True]])

In [39]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
a[...,0] == a[:, :, 0]

array([[ True,  True],
       [ True,  True]])

### A Few Basic Operations

In [42]:
a = np.array([45, 65, 76, 32, 99, 22])
a < 50

array([ True, False, False,  True, False,  True])

In [43]:
# 7.1
a = np.arange(8).reshape((2,4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
a.min(axis=1)

array([0, 4])

In [45]:
a.sum(axis=0)

array([ 4,  6,  8, 10])

In [46]:
a.mean(axis=1)

array([1.5, 5.5])

In [47]:
a.std(axis=1)

array([1.11803399, 1.11803399])

In [49]:
# 7.2
pi = np.pi
a = np.array([pi, pi/2, pi/4, pi/6])

np.degrees(a)

array([180.,  90.,  45.,  30.])

In [51]:
sin_a = np.sin(a)
sin_a

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 5.00000000e-01])

In [52]:
np.round(sin_a, 7)

array([0.       , 1.       , 0.7071068, 0.5      ])

In [53]:
a = np.arange(8).reshape((2, 4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [54]:
np.cumsum(a, axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22]])

In [55]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

### Creating Array Functions

#### Calculating a Moving Average

In [56]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

In [57]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [58]:
csum = np.cumsum(a)
csum

array([ 0,  1,  3,  6, 10, 15])

In [59]:
csum[3:] = csum[3:] - csum[:-3]
csum

array([ 0,  1,  3,  6,  9, 12])

In [60]:
a = np.arange(10)
moving_average(a, 4)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])